services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_PORT=5000
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data # Persist Redis data # I asked to add the mapped volume for Redis data persistence in the repository (should be a file mapped to the container)

volumes:
  redis-data: # Docker-managed volume for Redis data
