services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_PORT=5000
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data # Persist Redis data

volumes:
  redis-data: # Docker-managed volume for Redis data
